title: DPSN Client SDK Documentation
description: Documentation for the DPSN Node.js Client SDK
baseurl: ""
url: "https://dpsn-org.github.io/sdk-docs"

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true
theme: jekyll-theme-minimal
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git/

# Collections
collections:
  docs:
    output: true
    permalink: /:collection/:path/

# Defaults
defaults:
  # Root files
  - scope:
      path: ""
      type: pages
    values:
      layout: "default"
      toc: true
  # Documentation files
  - scope:
      path: "_docs"
      type: docs
    values:
      layout: "doc"
      toc: true

# GitHub Pages specific settings
github:
  repository: dpns-org/sdk-docs
  branch: main 